name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run build
      - run: bunx wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.cfut_A2LkdEfuLEta4UK2FAextBmcdtAPaUU3a5irl87A7598ae9a }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.be6dbe9ea0c35865215242f65ad00834 }}
